# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  local.credit:
    site_hosts:
      - canonical: local.dev
        redirects:
          - www.local.dev
    local_path: ../lc # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@local.dev
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
